[[http://spacemacs.org/][Spacemacs]] inspired configuration for [[http://www.hammerspoon.org/][Hammerspoon]]

#+BEGIN_SRC bash
git clone https://github.com/agzam/spacehammer ~/.hammerspoon
#+END_SRC

** Why?
   I love Vim keybindings and I needed to find a better, more efficient way to manage windows and jump between the apps.
   Ideally I wanted to stay in the home row and control as much as I can with ~HJKL~ keys. Adding tens (possibly hundreds) of key-combo shortcuts for every single desirable action is not a good solution.

   Hammerspoon is incredibly powerful tool, and it has allowed me to take my workflow to a completely different level. Jumping between apps, controlling windows, searching things has become such a joyful experience. And no need to learn and memorize multitude of keystrokes. Or have to use the mouse or arrow keys.
**** Note
     Main keybinding is set to ~Cmd SPC~, that by default might be set for something else in OS X. *You're gonna need to clear that key combination* . Go to your Preferences/Keyboard, find associated keybinding and *clear it out*, simply unchecking the checkbox may not be sufficient.
     If you choose to have some different key combo for Spacehammer's default action - you're gonna have to modify ~/.hammerspoon/init.lua.

*** ~Cmd SPC w~ - Windows
    - ~Cmd + hjkl~ - for jumping between application windows
    - ~hjkl~ - moving windows around halves of the screen
    - ~n/p~ - moving to prev/next monitor
    - ~Alt + hjkl~ - moving in increments
    - ~Shift + hjkl~ - re-sizing active window
    - ~g~ - resizing with [[http://www.hammerspoon.org/docs/hs.grid.html][hs.grid]]
    - ~m~ - maximize active window
    - ~u~ - undo window operation 

*** ~Cmd SPC a~ - Apps
    - ~e~ - Emacs
    - ~c~ - Chrome
    - ~t~ - Terminal
    - ~s~ - Slack
    - ~b~ - Brave

*** ~Cmd SPC SPC~ - open Alfred search bar

** Other features
*** Slack Desktop Client enhancements
     - Switching to Slack via "Apps" modal automatically opens Slack's "Jump to" dialog
     - Scrolling current Slack thread with ~C-j~, ~C-k~
     - Jumping to the end of the thread with ~C-g~
     - Adding emoji to the last message - ~Cmd-I~ (sorry, but default ~Cmd-Shift+\~ horribly inconvenient) 

** TODO: [0/7]
   - [ ] ~jk~ for exiting modals
   - [ ] I'd like to find a way to jump to Chrome window with specific profile (right now ~Ctrl-Cmd SPC a b~ will switch to Chrome, but if you have multiple profiles you have to manually find the one you need) 
   - [ ] I use Chrome Dev-tools a lot, would be nice to automate things, e.g.: Keybinding that opens devtools and creates a vertical split with main window on the left and devtools on the right
   - [ ] Being able to enter selected passwords from keychain (not sure how I'm gonna do this one)
   - [ ] Better than default HUD display
   - [ ] Org-pomodoro (show current task in menubar)
   - [ ] Disable currently non-available keys. Only specified keys should be usable if a mode

** Customizing
I think this part is pretty easy. Lua is extremely simple language. I shamelessly borrowed this [[https://github.com/kyleconroy/lua-state-machine][state-machine implementation]], and that makes adding new modes and extending current ones a piece of cake.
